package com.kel9.fproject;

import javax.swing.JFrame;
import javax.swing.JPopupMenu;
import javax.swing.Popup;
import javax.swing.PopupFactory;

import com.kel9.fproject.Permintaan;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author x1nx3r
 */
public class DashboardUI extends javax.swing.JFrame {
    private WindowStateManager windowManager; 
    private Permintaan requestForm;
    /**
     * Creates new form dashboardUI
     * @param windowManager
     */
    public DashboardUI(WindowStateManager windowManager) {
        this.windowManager = windowManager;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        card1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        request_title = new javax.swing.JLabel();
        card = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        send_title = new javax.swing.JLabel();
        card2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        product_title = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        transaction_table = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btn_add = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        pengiriman = new javax.swing.JPanel();
        addnew = new javax.swing.JPanel();
        kirim1 = new java.awt.Label();
        text1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        kirim2 = new java.awt.Label();
        text2 = new javax.swing.JTextField();
        kirim3 = new java.awt.Label();
        text3 = new javax.swing.JTextField();
        kirim4 = new java.awt.Label();
        kirim5 = new java.awt.Label();
        text5 = new javax.swing.JTextField();
        kirim6 = new java.awt.Label();
        text6 = new javax.swing.JTextField();
        title = new java.awt.Label();
        jComboBox1 = new javax.swing.JComboBox<>();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        listitem = new javax.swing.JScrollPane();
        table_pengiriman = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UPN Warehouse Management");
        getContentPane().setLayout(new java.awt.CardLayout());

        jTabbedPane2.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.Y_AXIS));

        jPanel4.setBackground(new java.awt.Color(238, 238, 238));
        jPanel4.setMaximumSize(new java.awt.Dimension(32767, 200));
        jPanel4.setPreferredSize(new java.awt.Dimension(1270, 200));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 100, 50));

        card1.setBackground(new java.awt.Color(255, 255, 255));
        card1.setMaximumSize(new java.awt.Dimension(200, 32767));
        card1.setMinimumSize(new java.awt.Dimension(200, 56));
        card1.setPreferredSize(new java.awt.Dimension(200, 100));
        card1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 20));

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 173, 181));
        jLabel5.setText("300");
        jLabel5.setPreferredSize(new java.awt.Dimension(100, 18));
        card1.add(jLabel5);

        request_title.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        request_title.setForeground(new java.awt.Color(57, 62, 70));
        request_title.setText("Permintaan");
        request_title.setPreferredSize(new java.awt.Dimension(100, 18));
        card1.add(request_title);

        jPanel4.add(card1);

        card.setBackground(new java.awt.Color(255, 255, 255));
        card.setMaximumSize(new java.awt.Dimension(200, 32767));
        card.setMinimumSize(new java.awt.Dimension(200, 56));
        card.setPreferredSize(new java.awt.Dimension(200, 100));
        card.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 20));

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 173, 181));
        jLabel3.setText("250");
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 18));
        card.add(jLabel3);

        send_title.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        send_title.setForeground(new java.awt.Color(57, 62, 70));
        send_title.setText("Terkirim");
        send_title.setPreferredSize(new java.awt.Dimension(100, 18));
        card.add(send_title);

        jPanel4.add(card);

        card2.setBackground(new java.awt.Color(255, 255, 255));
        card2.setMaximumSize(new java.awt.Dimension(200, 32767));
        card2.setMinimumSize(new java.awt.Dimension(200, 56));
        card2.setPreferredSize(new java.awt.Dimension(200, 100));
        card2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 20));

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 173, 181));
        jLabel7.setText("500");
        jLabel7.setPreferredSize(new java.awt.Dimension(100, 18));
        card2.add(jLabel7);

        product_title.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        product_title.setForeground(new java.awt.Color(57, 62, 70));
        product_title.setText("Barang");
        product_title.setPreferredSize(new java.awt.Dimension(100, 18));
        card2.add(product_title);

        jPanel4.add(card2);

        jPanel6.add(jPanel4);

        jScrollPane1.setForeground(new java.awt.Color(153, 0, 255));

        transaction_table.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        transaction_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "No", "Tanggal", "Kode Pesanan", "Pelanggan", "Total Pesanan", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        transaction_table.setRowHeight(25);
        jScrollPane1.setViewportView(transaction_table);
        if (transaction_table.getColumnModel().getColumnCount() > 0) {
            transaction_table.getColumnModel().getColumn(0).setResizable(false);
            transaction_table.getColumnModel().getColumn(0).setPreferredWidth(20);
            transaction_table.getColumnModel().getColumn(1).setResizable(false);
            transaction_table.getColumnModel().getColumn(2).setResizable(false);
            transaction_table.getColumnModel().getColumn(3).setPreferredWidth(100);
            transaction_table.getColumnModel().getColumn(4).setResizable(false);
            transaction_table.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel6.add(jScrollPane1);

        jTabbedPane2.addTab("Dashboard", jPanel6);

        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.Y_AXIS));

        jPanel3.setMaximumSize(new java.awt.Dimension(32767, 120));
        jPanel3.setMinimumSize(new java.awt.Dimension(379, 20));
        jPanel3.setPreferredSize(new java.awt.Dimension(1182, 150));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 50));

        btn_add.setText("Tambah Permintaan");
        btn_add.setPreferredSize(new java.awt.Dimension(163, 40));
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        jPanel3.add(btn_add);

        jTextField1.setPreferredSize(new java.awt.Dimension(500, 40));
        jPanel3.add(jTextField1);

        jButton1.setText("Cari");
        jButton1.setPreferredSize(new java.awt.Dimension(72, 40));
        jPanel3.add(jButton1);

        jPanel7.add(jPanel3);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Kode Pemesanan", "Tanggal Pemesanan", "Jenis Produk", "Pelanggan", "Jumlah Pemesanan", "Status Pemesanan"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel7.add(jScrollPane2);

        jTabbedPane2.addTab("Permintaan", jPanel7);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1182, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 748, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Persediaan", jPanel1);

        pengiriman.setLayout(new javax.swing.BoxLayout(pengiriman, javax.swing.BoxLayout.Y_AXIS));

        addnew.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addnew.setMaximumSize(new java.awt.Dimension(32767, 120));
        addnew.setMinimumSize(new java.awt.Dimension(379, 20));
        addnew.setPreferredSize(new java.awt.Dimension(1182, 400));
        addnew.setLayout(new java.awt.GridBagLayout());

        kirim1.setText("Pelanggan");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        addnew.add(kirim1, gridBagConstraints);

        text1.setPreferredSize(new java.awt.Dimension(300, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        addnew.add(text1, gridBagConstraints);

        jButton4.setText("TAMBAH");
        jButton4.setAlignmentX(0.5F);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton4.setPreferredSize(new java.awt.Dimension(100, 40));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        addnew.add(jButton4, gridBagConstraints);

        kirim2.setText("Jenis Produk");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        addnew.add(kirim2, gridBagConstraints);

        text2.setPreferredSize(new java.awt.Dimension(300, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        addnew.add(text2, gridBagConstraints);

        kirim3.setText("Biaya Pengiriman");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        addnew.add(kirim3, gridBagConstraints);

        text3.setPreferredSize(new java.awt.Dimension(300, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        addnew.add(text3, gridBagConstraints);

        kirim4.setText("Jenis Pengiriman");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        addnew.add(kirim4, gridBagConstraints);

        kirim5.setText("Tanggal Pengiriman");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        addnew.add(kirim5, gridBagConstraints);

        text5.setPreferredSize(new java.awt.Dimension(300, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        addnew.add(text5, gridBagConstraints);

        kirim6.setText("Kode Pemesanan");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        addnew.add(kirim6, gridBagConstraints);

        text6.setPreferredSize(new java.awt.Dimension(300, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        addnew.add(text6, gridBagConstraints);

        title.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        title.setText("Tambah Data Pengiriman Baru");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        addnew.add(title, gridBagConstraints);
        title.getAccessibleContext().setAccessibleName("");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Same Day", "Cepat", "Reguler", "Kargo" }));
        jComboBox1.setPreferredSize(new java.awt.Dimension(300, 30));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        addnew.add(jComboBox1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(1, 0, 1, 0);
        addnew.add(filler2, gridBagConstraints);

        pengiriman.add(addnew);

        table_pengiriman.setModel(DatabaseConnect.populatePengirimanTable());
        listitem.setViewportView(table_pengiriman);

        pengiriman.add(listitem);

        jTabbedPane2.addTab("Pengiriman", pengiriman);

        getContentPane().add(jTabbedPane2, "card2");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        requestForm = new Permintaan();        
        requestForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        requestForm.setLocationRelativeTo(null);
        requestForm.setVisible(true);
    }//GEN-LAST:event_btn_addActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addnew;
    private javax.swing.JButton btn_add;
    private javax.swing.JPanel card;
    private javax.swing.JPanel card1;
    private javax.swing.JPanel card2;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private java.awt.Label kirim1;
    private java.awt.Label kirim2;
    private java.awt.Label kirim3;
    private java.awt.Label kirim4;
    private java.awt.Label kirim5;
    private java.awt.Label kirim6;
    private javax.swing.JScrollPane listitem;
    private javax.swing.JPanel pengiriman;
    private javax.swing.JLabel product_title;
    private javax.swing.JLabel request_title;
    private javax.swing.JLabel send_title;
    private javax.swing.JTable table_pengiriman;
    private javax.swing.JTextField text1;
    private javax.swing.JTextField text2;
    private javax.swing.JTextField text3;
    private javax.swing.JTextField text5;
    private javax.swing.JTextField text6;
    private java.awt.Label title;
    private javax.swing.JTable transaction_table;
    // End of variables declaration//GEN-END:variables
}
