package com.kel9.fproject;

import java.awt.Color;

import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPopupMenu;
import javax.swing.JTable;
import javax.swing.Popup;
import javax.swing.PopupFactory;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;

import com.toedter.calendar.JDateChooser;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;


import com.kel9.fproject.PermintaanUbah;
import java.sql.Date;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author x1nx3r
 */
public class DashboardUI extends javax.swing.JFrame {
    private WindowStateManager windowManager; 
    private PermintaanUbah permintaanUbah;
    private PersediaanUbah persediaanUbah;
    private PengirimanUbah pengirimanUbah;
    private Permintaan requestForm;

    // row id each table cell
    private int idSelected = 0;

    /**
     * Creates new form dashboardUI
     * @param windowManager
     */
    public DashboardUI(WindowStateManager windowManager) {
        this.windowManager = windowManager;
        initComponents();
        showDashboardInformation();
        updateDashboardTable();
        this.setAllTable();
    }

    private void updateDashboardTable() {
        this.permintaan_table_dashboard.setModel(DatabaseConnect.permintaanTableDashboard());
        this.persediaan_table_dashboard.setModel(DatabaseConnect.persediaanTableDashboard());
        this.pengiriman_table_dashboard.setModel(DatabaseConnect.pengirimanTableDashboard());
        this.showDashboardInformation();
    }

    public void setAllTable(){
        setTable(this.request_table,0);
        setTable(this.supply_table,0);
        setTable(this.delivery_table,0);        
        setTable(this.permintaan_table_dashboard,1);
        setTable(this.persediaan_table_dashboard,2);
        setTable(this.pengiriman_table_dashboard,-1); 
    }

    public void setTableDashboard(){
        setTable(this.permintaan_table_dashboard,1);
        setTable(this.persediaan_table_dashboard,2);
        setTable(this.pengiriman_table_dashboard,-1); 
    }
    private void setTable(JTable tableName, int columnNumber) {
        String defaultFont = "Liberation Sans";

        //? header
        JTableHeader header = tableName.getTableHeader();
        Dimension headerSize = header.getPreferredSize();
        header.setFont(new Font(defaultFont, Font.BOLD, 18));     
        header.setPreferredSize(new Dimension(headerSize.width, 40));
        header.setBorder(null);
        header.setBackground(Color.decode("#00ADB5"));
        header.setForeground(Color.WHITE);

        //? column

        //? set center
        final TableColumnModel columnModel = tableName.getColumnModel();    
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        columnModel.getColumn(0).setCellRenderer(centerRenderer);

        for (int column = 1; column < tableName.getColumnCount(); column++) {
            int width = 15; // Min width
            for (int row = 0; row < tableName.getRowCount(); row++) {
                TableCellRenderer renderer = tableName.getCellRenderer(row, column);
                Component comp = tableName.prepareRenderer(renderer, row, column);
                width = Math.max(comp.getPreferredSize().width +1 , width);
            }
            if(width > 300)
                width=300;
            columnModel.getColumn(column).setPreferredWidth(width);
        }

        if (columnNumber >= 0){
            columnModel.getColumn(columnNumber).setMaxWidth(80);
            columnModel.getColumn(columnNumber).setPreferredWidth(80);
        }

    }

    private void showDashboardInformation(){
        int[] tablesRowCount = DatabaseConnect.dashboardInformation();
        this.request_value.setText(Integer.toString(tablesRowCount[0]));
        this.supply_value.setText(Integer.toString(tablesRowCount[1]));
        this.delivery_value.setText(Integer.toString(tablesRowCount[2]));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        container_tab = new javax.swing.JTabbedPane();
        dashboard = new javax.swing.JPanel();
        cards_contianer = new javax.swing.JPanel();
        card1 = new javax.swing.JPanel();
        request_value = new javax.swing.JLabel();
        request_title = new javax.swing.JLabel();
        card = new javax.swing.JPanel();
        supply_value = new javax.swing.JLabel();
        send_title = new javax.swing.JLabel();
        card2 = new javax.swing.JPanel();
        delivery_value = new javax.swing.JLabel();
        product_title = new javax.swing.JLabel();
        tables_panel = new javax.swing.JPanel();
        permintaan_container = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        permintaan_table_dashboard = new javax.swing.JTable();
        jSeparator11 = new javax.swing.JSeparator();
        permintaan_container1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        persediaan_table_dashboard = new javax.swing.JTable();
        jSeparator12 = new javax.swing.JSeparator();
        permintaan_container2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        pengiriman_table_dashboard = new javax.swing.JTable();
        require = new javax.swing.JPanel();
        addnew2 = new javax.swing.JPanel();
        tambah_pengiriman_button2 = new javax.swing.JButton();
        kirim14 = new java.awt.Label();
        jenis_produk_field1 = new javax.swing.JTextField();
        kirim15 = new java.awt.Label();
        kirim16 = new java.awt.Label();
        kirim17 = new java.awt.Label();
        kirim18 = new java.awt.Label();
        kode_pesanan_permintaan = new javax.swing.JTextField();
        title2 = new java.awt.Label();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        tanggal_pesanan_field1 = new com.toedter.calendar.JDateChooser();
        pelanggan_field1 = new javax.swing.JTextField();
        jumlah_pesanan_field1 = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        ubah_permintaan_button = new javax.swing.JButton();
        kirim19 = new java.awt.Label();
        status_pemesanan_field1 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        request_table = new javax.swing.JTable();
        supply = new javax.swing.JPanel();
        addnew1 = new javax.swing.JPanel();
        kirim7 = new java.awt.Label();
        tambah_pengiriman_button1 = new javax.swing.JButton();
        nama_barang_field = new javax.swing.JTextField();
        kirim8 = new java.awt.Label();
        kategori_field = new javax.swing.JTextField();
        kirim9 = new java.awt.Label();
        kirim10 = new java.awt.Label();
        kirim11 = new java.awt.Label();
        kirim12 = new java.awt.Label();
        id_barang_field = new javax.swing.JTextField();
        title1 = new java.awt.Label();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        exp_date_field = new com.toedter.calendar.JDateChooser();
        lokasi_field = new javax.swing.JTextField();
        jumlah_field = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        ubah_persediaan_button = new javax.swing.JButton();
        listitem1 = new javax.swing.JScrollPane();
        supply_table = new javax.swing.JTable();
        pengiriman = new javax.swing.JPanel();
        addnew = new javax.swing.JPanel();
        kirim1 = new java.awt.Label();
        ubah_pengiriman_button = new javax.swing.JButton();
        pelanggan_field = new javax.swing.JTextField();
        kirim2 = new java.awt.Label();
        jenis_produk_field = new javax.swing.JTextField();
        kirim3 = new java.awt.Label();
        biaya_pengiriman_field = new javax.swing.JTextField();
        kirim4 = new java.awt.Label();
        kirim5 = new java.awt.Label();
        kirim6 = new java.awt.Label();
        kode_pemesanan_field = new javax.swing.JTextField();
        title = new java.awt.Label();
        jenis_pengiriman_field = new javax.swing.JComboBox<>();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        tanggal_pengiriman_field = new com.toedter.calendar.JDateChooser();
        jSeparator9 = new javax.swing.JSeparator();
        tambah_pengiriman_button3 = new javax.swing.JButton();
        listitem = new javax.swing.JScrollPane();
        delivery_table = new javax.swing.JTable();
        setting = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        title_container = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        company_data = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        company_name = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jTextField2 = new javax.swing.JTextField();
        company_address = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jTextField4 = new javax.swing.JTextField();
        company_number = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jTextField5 = new javax.swing.JTextField();
        company_email = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jTextField6 = new javax.swing.JTextField();
        company_email1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jTextField7 = new javax.swing.JTextField();
        button_container = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        btn_logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UPN Warehouse Management");
        setPreferredSize(new java.awt.Dimension(1500, 900));
        getContentPane().setLayout(new java.awt.CardLayout());

        container_tab.setBackground(new java.awt.Color(246, 246, 246));
        container_tab.setFocusable(false);
        container_tab.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        container_tab.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                container_tabStateChanged(evt);
            }
        });

        dashboard.setLayout(new javax.swing.BoxLayout(dashboard, javax.swing.BoxLayout.Y_AXIS));

        cards_contianer.setBackground(new java.awt.Color(238, 238, 238));
        cards_contianer.setMaximumSize(new java.awt.Dimension(32767, 200));
        cards_contianer.setPreferredSize(new java.awt.Dimension(1270, 200));
        cards_contianer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cards_contianerMouseEntered(evt);
            }
        });
        cards_contianer.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 100, 50));

        card1.setBackground(new java.awt.Color(255, 255, 255));
        card1.setMaximumSize(new java.awt.Dimension(500, 32767));
        card1.setMinimumSize(new java.awt.Dimension(200, 56));
        card1.setPreferredSize(new java.awt.Dimension(300, 200));
        card1.setRequestFocusEnabled(false);
        card1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 20));

        request_value.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        request_value.setForeground(new java.awt.Color(0, 173, 181));
        request_value.setText("300");
        request_value.setPreferredSize(new java.awt.Dimension(200, 50));
        card1.add(request_value);

        request_title.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        request_title.setForeground(new java.awt.Color(153, 153, 153));
        request_title.setText("Permintaan");
        request_title.setPreferredSize(new java.awt.Dimension(200, 18));
        card1.add(request_title);

        cards_contianer.add(card1);

        card.setBackground(new java.awt.Color(255, 255, 255));
        card.setMaximumSize(new java.awt.Dimension(500, 32767));
        card.setMinimumSize(new java.awt.Dimension(200, 56));
        card.setPreferredSize(new java.awt.Dimension(300, 200));
        card.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 20));

        supply_value.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        supply_value.setForeground(new java.awt.Color(0, 173, 181));
        supply_value.setText("250");
        supply_value.setPreferredSize(new java.awt.Dimension(200, 40));
        card.add(supply_value);

        send_title.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        send_title.setForeground(new java.awt.Color(153, 153, 153));
        send_title.setText("Persediaan");
        send_title.setPreferredSize(new java.awt.Dimension(200, 18));
        card.add(send_title);

        cards_contianer.add(card);

        card2.setBackground(new java.awt.Color(255, 255, 255));
        card2.setMaximumSize(new java.awt.Dimension(500, 32767));
        card2.setMinimumSize(new java.awt.Dimension(200, 56));
        card2.setPreferredSize(new java.awt.Dimension(300, 200));
        card2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 20));

        delivery_value.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        delivery_value.setForeground(new java.awt.Color(0, 173, 181));
        delivery_value.setText("500");
        delivery_value.setPreferredSize(new java.awt.Dimension(200, 40));
        card2.add(delivery_value);

        product_title.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        product_title.setForeground(new java.awt.Color(153, 153, 153));
        product_title.setText("Pengiriman");
        product_title.setPreferredSize(new java.awt.Dimension(200, 18));
        card2.add(product_title);

        cards_contianer.add(card2);

        dashboard.add(cards_contianer);

        tables_panel.setLayout(new javax.swing.BoxLayout(tables_panel, javax.swing.BoxLayout.X_AXIS));

        permintaan_container.setMaximumSize(new java.awt.Dimension(2147483647, 500));
        permintaan_container.setMinimumSize(new java.awt.Dimension(400, 400));
        permintaan_container.setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 173, 181));
        jLabel3.setText("Permintaan");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 20;
        permintaan_container.add(jLabel3, gridBagConstraints);

        jScrollPane3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane3.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jScrollPane3.setMaximumSize(new java.awt.Dimension(32767, 500));
        jScrollPane3.setMinimumSize(new java.awt.Dimension(16, 500));
        jScrollPane3.setPreferredSize(new java.awt.Dimension(452, 400));

        permintaan_table_dashboard.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        permintaan_table_dashboard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Kode Pemesanan", "Jumlah", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        permintaan_table_dashboard.setGridColor(new java.awt.Color(255, 255, 255));
        permintaan_table_dashboard.setMaximumSize(new java.awt.Dimension(2147483647, 500));
        permintaan_table_dashboard.setMinimumSize(new java.awt.Dimension(45, 500));
        permintaan_table_dashboard.setRequestFocusEnabled(false);
        permintaan_table_dashboard.setRowHeight(30);
        jScrollPane3.setViewportView(permintaan_table_dashboard);
        if (permintaan_table_dashboard.getColumnModel().getColumnCount() > 0) {
            permintaan_table_dashboard.getColumnModel().getColumn(0).setResizable(false);
            permintaan_table_dashboard.getColumnModel().getColumn(1).setResizable(false);
            permintaan_table_dashboard.getColumnModel().getColumn(2).setResizable(false);
        }

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        permintaan_container.add(jScrollPane3, gridBagConstraints);

        tables_panel.add(permintaan_container);

        jSeparator11.setMaximumSize(new java.awt.Dimension(10, 10));
        tables_panel.add(jSeparator11);

        permintaan_container1.setMaximumSize(new java.awt.Dimension(2147483647, 500));
        permintaan_container1.setMinimumSize(new java.awt.Dimension(400, 400));
        permintaan_container1.setLayout(new java.awt.GridBagLayout());

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 173, 181));
        jLabel5.setText("Persediaan");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 20;
        permintaan_container1.add(jLabel5, gridBagConstraints);

        jScrollPane4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane4.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jScrollPane4.setMaximumSize(new java.awt.Dimension(32767, 400));
        jScrollPane4.setMinimumSize(new java.awt.Dimension(16, 400));
        jScrollPane4.setPreferredSize(new java.awt.Dimension(452, 400));

        persediaan_table_dashboard.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        persediaan_table_dashboard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Kode Pemesanan", "Barang", "Jumlah"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        persediaan_table_dashboard.setGridColor(new java.awt.Color(255, 255, 255));
        persediaan_table_dashboard.setRowHeight(30);
        jScrollPane4.setViewportView(persediaan_table_dashboard);
        if (persediaan_table_dashboard.getColumnModel().getColumnCount() > 0) {
            persediaan_table_dashboard.getColumnModel().getColumn(0).setResizable(false);
            persediaan_table_dashboard.getColumnModel().getColumn(1).setResizable(false);
            persediaan_table_dashboard.getColumnModel().getColumn(2).setResizable(false);
        }

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        permintaan_container1.add(jScrollPane4, gridBagConstraints);

        tables_panel.add(permintaan_container1);

        jSeparator12.setMaximumSize(new java.awt.Dimension(10, 10));
        tables_panel.add(jSeparator12);

        permintaan_container2.setMaximumSize(new java.awt.Dimension(2147483647, 500));
        permintaan_container2.setMinimumSize(new java.awt.Dimension(400, 400));
        permintaan_container2.setLayout(new java.awt.GridBagLayout());

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 173, 181));
        jLabel7.setText("Pengiriman");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 20;
        permintaan_container2.add(jLabel7, gridBagConstraints);

        jScrollPane5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane5.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jScrollPane5.setMaximumSize(new java.awt.Dimension(32767, 400));
        jScrollPane5.setMinimumSize(new java.awt.Dimension(16, 400));
        jScrollPane5.setPreferredSize(new java.awt.Dimension(452, 400));

        pengiriman_table_dashboard.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        pengiriman_table_dashboard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Kode Pemesanan", "Pelanggan", "Tanggal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        pengiriman_table_dashboard.setGridColor(new java.awt.Color(255, 255, 255));
        pengiriman_table_dashboard.setRowHeight(30);
        jScrollPane5.setViewportView(pengiriman_table_dashboard);
        if (pengiriman_table_dashboard.getColumnModel().getColumnCount() > 0) {
            pengiriman_table_dashboard.getColumnModel().getColumn(0).setResizable(false);
            pengiriman_table_dashboard.getColumnModel().getColumn(1).setResizable(false);
            pengiriman_table_dashboard.getColumnModel().getColumn(2).setResizable(false);
        }

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        permintaan_container2.add(jScrollPane5, gridBagConstraints);

        tables_panel.add(permintaan_container2);

        dashboard.add(tables_panel);

        container_tab.addTab("Dashboard", dashboard);

        require.setBackground(new java.awt.Color(246, 246, 246));
        require.setLayout(new javax.swing.BoxLayout(require, javax.swing.BoxLayout.Y_AXIS));

        addnew2.setBackground(new java.awt.Color(246, 246, 246));
        addnew2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addnew2.setMaximumSize(new java.awt.Dimension(32767, 120));
        addnew2.setMinimumSize(new java.awt.Dimension(379, 20));
        addnew2.setPreferredSize(new java.awt.Dimension(1182, 400));
        addnew2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addnew2MouseEntered(evt);
            }
        });
        addnew2.setLayout(new java.awt.GridBagLayout());

        tambah_pengiriman_button2.setBackground(new java.awt.Color(0, 173, 181));
        tambah_pengiriman_button2.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        tambah_pengiriman_button2.setForeground(new java.awt.Color(255, 255, 255));
        tambah_pengiriman_button2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/plus.png"))); // NOI18N
        tambah_pengiriman_button2.setText("TAMBAH");
        tambah_pengiriman_button2.setAlignmentX(0.5F);
        tambah_pengiriman_button2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        tambah_pengiriman_button2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tambah_pengiriman_button2.setIconTextGap(10);
        tambah_pengiriman_button2.setMaximumSize(new java.awt.Dimension(350, 40));
        tambah_pengiriman_button2.setMinimumSize(new java.awt.Dimension(350, 40));
        tambah_pengiriman_button2.setPreferredSize(new java.awt.Dimension(300, 40));
        tambah_pengiriman_button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambah_pengiriman_button2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        addnew2.add(tambah_pengiriman_button2, gridBagConstraints);

        kirim14.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        kirim14.setText("Status Pemesanan");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        addnew2.add(kirim14, gridBagConstraints);

        jenis_produk_field1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jenis_produk_field1.setMaximumSize(new java.awt.Dimension(350, 24));
        jenis_produk_field1.setMinimumSize(new java.awt.Dimension(350, 24));
        jenis_produk_field1.setPreferredSize(new java.awt.Dimension(350, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        addnew2.add(jenis_produk_field1, gridBagConstraints);

        kirim15.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        kirim15.setText("Pelanggan");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        addnew2.add(kirim15, gridBagConstraints);

        kirim16.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        kirim16.setText("Jumlah Pesanan");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        addnew2.add(kirim16, gridBagConstraints);

        kirim17.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        kirim17.setText("Tanggal Pengiriman");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        addnew2.add(kirim17, gridBagConstraints);

        kirim18.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        kirim18.setText("Kode Pemesanan");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        addnew2.add(kirim18, gridBagConstraints);

        kode_pesanan_permintaan.setEditable(false);
        kode_pesanan_permintaan.setBackground(new java.awt.Color(239, 239, 239));
        kode_pesanan_permintaan.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        kode_pesanan_permintaan.setFocusable(false);
        kode_pesanan_permintaan.setMaximumSize(new java.awt.Dimension(350, 24));
        kode_pesanan_permintaan.setMinimumSize(new java.awt.Dimension(350, 24));
        kode_pesanan_permintaan.setPreferredSize(new java.awt.Dimension(350, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        addnew2.add(kode_pesanan_permintaan, gridBagConstraints);

        title2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        title2.setText("Tambah Data Permintaan Baru");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        addnew2.add(title2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(1, 0, 1, 0);
        addnew2.add(filler4, gridBagConstraints);

        tanggal_pesanan_field1.setMaximumSize(new java.awt.Dimension(350, 24));
        tanggal_pesanan_field1.setMinimumSize(new java.awt.Dimension(350, 24));
        tanggal_pesanan_field1.setPreferredSize(new java.awt.Dimension(350, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 10;
        addnew2.add(tanggal_pesanan_field1, gridBagConstraints);

        pelanggan_field1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        pelanggan_field1.setMaximumSize(new java.awt.Dimension(350, 24));
        pelanggan_field1.setMinimumSize(new java.awt.Dimension(350, 24));
        pelanggan_field1.setPreferredSize(new java.awt.Dimension(350, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        addnew2.add(pelanggan_field1, gridBagConstraints);

        jumlah_pesanan_field1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jumlah_pesanan_field1.setMaximumSize(new java.awt.Dimension(350, 24));
        jumlah_pesanan_field1.setMinimumSize(new java.awt.Dimension(350, 24));
        jumlah_pesanan_field1.setPreferredSize(new java.awt.Dimension(350, 24));
        jumlah_pesanan_field1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlah_pesanan_field1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 10;
        addnew2.add(jumlah_pesanan_field1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        addnew2.add(jSeparator10, gridBagConstraints);

        ubah_permintaan_button.setBackground(new java.awt.Color(102, 102, 255));
        ubah_permintaan_button.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        ubah_permintaan_button.setForeground(new java.awt.Color(255, 255, 255));
        ubah_permintaan_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/update.png"))); // NOI18N
        ubah_permintaan_button.setText("UBAH");
        ubah_permintaan_button.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        ubah_permintaan_button.setIconTextGap(10);
        ubah_permintaan_button.setMaximumSize(new java.awt.Dimension(350, 40));
        ubah_permintaan_button.setMinimumSize(new java.awt.Dimension(350, 40));
        ubah_permintaan_button.setPreferredSize(new java.awt.Dimension(300, 40));
        ubah_permintaan_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubah_permintaan_buttonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        addnew2.add(ubah_permintaan_button, gridBagConstraints);

        kirim19.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        kirim19.setText("Jenis Produk");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        addnew2.add(kirim19, gridBagConstraints);

        status_pemesanan_field1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        status_pemesanan_field1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diajukan", "Selesai", "Dibatalkan" }));
        status_pemesanan_field1.setLightWeightPopupEnabled(false);
        status_pemesanan_field1.setMaximumSize(new java.awt.Dimension(350, 24));
        status_pemesanan_field1.setMinimumSize(new java.awt.Dimension(350, 24));
        status_pemesanan_field1.setPreferredSize(new java.awt.Dimension(350, 24));
        status_pemesanan_field1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                status_pemesanan_field1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        addnew2.add(status_pemesanan_field1, gridBagConstraints);

        require.add(addnew2);

        jScrollPane2.setBackground(new java.awt.Color(246, 246, 246));
        jScrollPane2.setBorder(null);

        request_table.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        request_table.setModel(DatabaseConnect.populatePermintaanTable());
        request_table.setGridColor(new java.awt.Color(255, 255, 255));
        request_table.setRowHeight(35);
        request_table.setRowMargin(5);
        request_table.setShowGrid(false);
        request_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                request_tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(request_table);

        require.add(jScrollPane2);

        container_tab.addTab("Permintaan", require);

        supply.setLayout(new javax.swing.BoxLayout(supply, javax.swing.BoxLayout.Y_AXIS));

        addnew1.setBackground(new java.awt.Color(246, 246, 246));
        addnew1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addnew1.setMaximumSize(new java.awt.Dimension(32767, 120));
        addnew1.setMinimumSize(new java.awt.Dimension(379, 20));
        addnew1.setPreferredSize(new java.awt.Dimension(1182, 400));
        addnew1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addnew1MouseEntered(evt);
            }
        });
        addnew1.setLayout(new java.awt.GridBagLayout());

        kirim7.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        kirim7.setText("Nama Barang");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        addnew1.add(kirim7, gridBagConstraints);

        tambah_pengiriman_button1.setBackground(new java.awt.Color(0, 173, 181));
        tambah_pengiriman_button1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        tambah_pengiriman_button1.setForeground(new java.awt.Color(255, 255, 255));
        tambah_pengiriman_button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/plus.png"))); // NOI18N
        tambah_pengiriman_button1.setText("TAMBAH");
        tambah_pengiriman_button1.setAlignmentX(0.5F);
        tambah_pengiriman_button1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        tambah_pengiriman_button1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tambah_pengiriman_button1.setIconTextGap(10);
        tambah_pengiriman_button1.setMaximumSize(new java.awt.Dimension(340, 40));
        tambah_pengiriman_button1.setMinimumSize(new java.awt.Dimension(340, 40));
        tambah_pengiriman_button1.setPreferredSize(new java.awt.Dimension(250, 40));
        tambah_pengiriman_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambah_pengiriman_button1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        addnew1.add(tambah_pengiriman_button1, gridBagConstraints);

        nama_barang_field.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        nama_barang_field.setMaximumSize(new java.awt.Dimension(400, 24));
        nama_barang_field.setMinimumSize(new java.awt.Dimension(400, 24));
        nama_barang_field.setPreferredSize(new java.awt.Dimension(300, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        addnew1.add(nama_barang_field, gridBagConstraints);

        kirim8.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        kirim8.setText("Kategori");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        addnew1.add(kirim8, gridBagConstraints);

        kategori_field.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        kategori_field.setMaximumSize(new java.awt.Dimension(400, 24));
        kategori_field.setMinimumSize(new java.awt.Dimension(400, 24));
        kategori_field.setPreferredSize(new java.awt.Dimension(300, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        addnew1.add(kategori_field, gridBagConstraints);

        kirim9.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        kirim9.setText("Lokasi");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        addnew1.add(kirim9, gridBagConstraints);

        kirim10.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        kirim10.setText("Jumlah Barang");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        addnew1.add(kirim10, gridBagConstraints);

        kirim11.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        kirim11.setText("Tanggal Pengiriman");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        addnew1.add(kirim11, gridBagConstraints);

        kirim12.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        kirim12.setText("ID Barang");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        addnew1.add(kirim12, gridBagConstraints);

        id_barang_field.setEditable(false);
        id_barang_field.setBackground(new java.awt.Color(239, 239, 239));
        id_barang_field.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        id_barang_field.setFocusable(false);
        id_barang_field.setMaximumSize(new java.awt.Dimension(400, 24));
        id_barang_field.setMinimumSize(new java.awt.Dimension(400, 24));
        id_barang_field.setPreferredSize(new java.awt.Dimension(300, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        addnew1.add(id_barang_field, gridBagConstraints);

        title1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        title1.setText("Tambah Data Barang Baru");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        addnew1.add(title1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(1, 0, 1, 0);
        addnew1.add(filler3, gridBagConstraints);

        exp_date_field.setMaximumSize(new java.awt.Dimension(400, 24));
        exp_date_field.setMinimumSize(new java.awt.Dimension(400, 24));
        exp_date_field.setPreferredSize(new java.awt.Dimension(300, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipady = 10;
        addnew1.add(exp_date_field, gridBagConstraints);

        lokasi_field.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lokasi_field.setMaximumSize(new java.awt.Dimension(400, 24));
        lokasi_field.setMinimumSize(new java.awt.Dimension(400, 24));
        lokasi_field.setPreferredSize(new java.awt.Dimension(300, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        addnew1.add(lokasi_field, gridBagConstraints);

        jumlah_field.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jumlah_field.setMaximumSize(new java.awt.Dimension(400, 24));
        jumlah_field.setMinimumSize(new java.awt.Dimension(400, 24));
        jumlah_field.setPreferredSize(new java.awt.Dimension(300, 24));
        jumlah_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlah_fieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipady = 10;
        addnew1.add(jumlah_field, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        addnew1.add(jSeparator8, gridBagConstraints);

        ubah_persediaan_button.setBackground(new java.awt.Color(102, 102, 255));
        ubah_persediaan_button.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        ubah_persediaan_button.setForeground(new java.awt.Color(255, 255, 255));
        ubah_persediaan_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/update.png"))); // NOI18N
        ubah_persediaan_button.setText("UBAH");
        ubah_persediaan_button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        ubah_persediaan_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ubah_persediaan_button.setIconTextGap(10);
        ubah_persediaan_button.setMaximumSize(new java.awt.Dimension(340, 40));
        ubah_persediaan_button.setMinimumSize(new java.awt.Dimension(340, 40));
        ubah_persediaan_button.setPreferredSize(new java.awt.Dimension(250, 40));
        ubah_persediaan_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubah_persediaan_buttonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        addnew1.add(ubah_persediaan_button, gridBagConstraints);

        supply.add(addnew1);

        listitem1.setBackground(new java.awt.Color(246, 246, 246));

        supply_table.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        supply_table.setModel(DatabaseConnect.populatePersediaanTable()
        );
        supply_table.setGridColor(new java.awt.Color(255, 255, 255));
        supply_table.setRowHeight(35);
        supply_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supply_tableMouseClicked(evt);
            }
        });
        listitem1.setViewportView(supply_table);

        supply.add(listitem1);

        container_tab.addTab("Persediaan", supply);

        pengiriman.setLayout(new javax.swing.BoxLayout(pengiriman, javax.swing.BoxLayout.Y_AXIS));

        addnew.setBackground(new java.awt.Color(246, 246, 246));
        addnew.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addnew.setMaximumSize(new java.awt.Dimension(32767, 120));
        addnew.setMinimumSize(new java.awt.Dimension(379, 20));
        addnew.setPreferredSize(new java.awt.Dimension(1182, 400));
        addnew.setLayout(new java.awt.GridBagLayout());

        kirim1.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        kirim1.setText("Pelanggan");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        addnew.add(kirim1, gridBagConstraints);

        ubah_pengiriman_button.setBackground(new java.awt.Color(102, 102, 255));
        ubah_pengiriman_button.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        ubah_pengiriman_button.setForeground(new java.awt.Color(255, 255, 255));
        ubah_pengiriman_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/update.png"))); // NOI18N
        ubah_pengiriman_button.setText("UBAH");
        ubah_pengiriman_button.setAlignmentX(0.5F);
        ubah_pengiriman_button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        ubah_pengiriman_button.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ubah_pengiriman_button.setIconTextGap(10);
        ubah_pengiriman_button.setMaximumSize(new java.awt.Dimension(300, 40));
        ubah_pengiriman_button.setMinimumSize(new java.awt.Dimension(300, 40));
        ubah_pengiriman_button.setPreferredSize(new java.awt.Dimension(300, 40));
        ubah_pengiriman_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubah_pengiriman_buttonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        addnew.add(ubah_pengiriman_button, gridBagConstraints);

        pelanggan_field.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        pelanggan_field.setMaximumSize(new java.awt.Dimension(350, 24));
        pelanggan_field.setMinimumSize(new java.awt.Dimension(350, 24));
        pelanggan_field.setPreferredSize(new java.awt.Dimension(350, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        addnew.add(pelanggan_field, gridBagConstraints);

        kirim2.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        kirim2.setText("Jenis Produk");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        addnew.add(kirim2, gridBagConstraints);

        jenis_produk_field.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jenis_produk_field.setMaximumSize(new java.awt.Dimension(350, 24));
        jenis_produk_field.setMinimumSize(new java.awt.Dimension(350, 24));
        jenis_produk_field.setPreferredSize(new java.awt.Dimension(350, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        addnew.add(jenis_produk_field, gridBagConstraints);

        kirim3.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        kirim3.setText("Biaya Pengiriman");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        addnew.add(kirim3, gridBagConstraints);

        biaya_pengiriman_field.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        biaya_pengiriman_field.setMaximumSize(new java.awt.Dimension(350, 24));
        biaya_pengiriman_field.setMinimumSize(new java.awt.Dimension(350, 24));
        biaya_pengiriman_field.setPreferredSize(new java.awt.Dimension(350, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        addnew.add(biaya_pengiriman_field, gridBagConstraints);

        kirim4.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        kirim4.setText("Jenis Pengiriman");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        addnew.add(kirim4, gridBagConstraints);

        kirim5.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        kirim5.setText("Tanggal Pengiriman");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        addnew.add(kirim5, gridBagConstraints);

        kirim6.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        kirim6.setText("Kode Pemesanan");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        addnew.add(kirim6, gridBagConstraints);

        kode_pemesanan_field.setEditable(false);
        kode_pemesanan_field.setBackground(new java.awt.Color(239, 239, 239));
        kode_pemesanan_field.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        kode_pemesanan_field.setFocusable(false);
        kode_pemesanan_field.setMaximumSize(new java.awt.Dimension(350, 24));
        kode_pemesanan_field.setMinimumSize(new java.awt.Dimension(350, 24));
        kode_pemesanan_field.setPreferredSize(new java.awt.Dimension(350, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        addnew.add(kode_pemesanan_field, gridBagConstraints);

        title.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        title.setText("Tambah Data Pengiriman Baru");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        addnew.add(title, gridBagConstraints);
        title.getAccessibleContext().setAccessibleName("");

        jenis_pengiriman_field.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jenis_pengiriman_field.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Same Day", "Cepat", "Reguler", "Kargo" }));
        jenis_pengiriman_field.setMaximumSize(new java.awt.Dimension(350, 24));
        jenis_pengiriman_field.setMinimumSize(new java.awt.Dimension(350, 24));
        jenis_pengiriman_field.setPreferredSize(new java.awt.Dimension(350, 24));
        jenis_pengiriman_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenis_pengiriman_fieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        addnew.add(jenis_pengiriman_field, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(1, 0, 1, 0);
        addnew.add(filler2, gridBagConstraints);

        tanggal_pengiriman_field.setMaximumSize(new java.awt.Dimension(350, 24));
        tanggal_pengiriman_field.setMinimumSize(new java.awt.Dimension(350, 24));
        tanggal_pengiriman_field.setPreferredSize(new java.awt.Dimension(350, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 10;
        addnew.add(tanggal_pengiriman_field, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        addnew.add(jSeparator9, gridBagConstraints);

        tambah_pengiriman_button3.setBackground(new java.awt.Color(0, 173, 181));
        tambah_pengiriman_button3.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        tambah_pengiriman_button3.setForeground(new java.awt.Color(255, 255, 255));
        tambah_pengiriman_button3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/plus.png"))); // NOI18N
        tambah_pengiriman_button3.setText("TAMBAH");
        tambah_pengiriman_button3.setAlignmentX(0.5F);
        tambah_pengiriman_button3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        tambah_pengiriman_button3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tambah_pengiriman_button3.setIconTextGap(10);
        tambah_pengiriman_button3.setMaximumSize(new java.awt.Dimension(300, 40));
        tambah_pengiriman_button3.setMinimumSize(new java.awt.Dimension(300, 40));
        tambah_pengiriman_button3.setPreferredSize(new java.awt.Dimension(300, 40));
        tambah_pengiriman_button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambah_pengiriman_button3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        addnew.add(tambah_pengiriman_button3, gridBagConstraints);

        pengiriman.add(addnew);

        listitem.setBackground(new java.awt.Color(246, 246, 246));

        delivery_table.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        delivery_table.setModel(DatabaseConnect.populatePengirimanTable()
        );
        delivery_table.setGridColor(new java.awt.Color(255, 255, 255));
        delivery_table.setRowHeight(35);
        delivery_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delivery_tableMouseClicked(evt);
            }
        });
        listitem.setViewportView(delivery_table);

        pengiriman.add(listitem);

        container_tab.addTab("Pengiriman", pengiriman);

        setting.setBackground(new java.awt.Color(255, 255, 255));
        setting.setLayout(new javax.swing.BoxLayout(setting, javax.swing.BoxLayout.Y_AXIS));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(246, 246, 246));
        jSeparator1.setMaximumSize(new java.awt.Dimension(32767, 100));
        jSeparator1.setMinimumSize(new java.awt.Dimension(0, 100));
        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 50));
        setting.add(jSeparator1);

        title_container.setBackground(new java.awt.Color(255, 255, 255));
        title_container.setMaximumSize(new java.awt.Dimension(32767, 100));
        title_container.setPreferredSize(new java.awt.Dimension(1182, 100));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 173, 181));
        jLabel1.setText("Pengaturan");
        title_container.add(jLabel1);

        setting.add(title_container);

        company_data.setBackground(new java.awt.Color(255, 255, 255));
        company_data.setMaximumSize(new java.awt.Dimension(700, 50));
        company_data.setPreferredSize(new java.awt.Dimension(1182, 200));
        company_data.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 5));

        jLabel9.setBackground(new java.awt.Color(0, 173, 181));
        jLabel9.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 173, 181));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Data Perusahaan");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        company_data.add(jLabel9);

        setting.add(company_data);

        company_name.setBackground(new java.awt.Color(255, 255, 255));
        company_name.setMaximumSize(new java.awt.Dimension(700, 50));
        company_name.setMinimumSize(new java.awt.Dimension(110, 50));
        company_name.setPreferredSize(new java.awt.Dimension(1182, 50));
        company_name.setLayout(new javax.swing.BoxLayout(company_name, javax.swing.BoxLayout.X_AXIS));

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jLabel2.setText("Nama Perusahaan");
        jLabel2.setMaximumSize(new java.awt.Dimension(200, 26));
        jLabel2.setMinimumSize(new java.awt.Dimension(200, 26));
        jLabel2.setPreferredSize(new java.awt.Dimension(200, 26));
        company_name.add(jLabel2);

        jSeparator2.setForeground(new java.awt.Color(242, 242, 242));
        jSeparator2.setMaximumSize(new java.awt.Dimension(200, 32767));
        jSeparator2.setMinimumSize(new java.awt.Dimension(200, 10));
        jSeparator2.setPreferredSize(new java.awt.Dimension(100, 10));
        company_name.add(jSeparator2);

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2.setFont(new java.awt.Font("Liberation Sans", 0, 20)); // NOI18N
        jTextField2.setText("PT. Pencari Berkah");
        jTextField2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextField2.setMaximumSize(new java.awt.Dimension(500, 2147483647));
        jTextField2.setMinimumSize(new java.awt.Dimension(500, 24));
        jTextField2.setPreferredSize(new java.awt.Dimension(300, 24));
        company_name.add(jTextField2);

        setting.add(company_name);

        company_address.setBackground(new java.awt.Color(255, 255, 255));
        company_address.setMaximumSize(new java.awt.Dimension(700, 50));
        company_address.setMinimumSize(new java.awt.Dimension(110, 50));
        company_address.setPreferredSize(new java.awt.Dimension(1182, 50));
        company_address.setLayout(new javax.swing.BoxLayout(company_address, javax.swing.BoxLayout.X_AXIS));

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jLabel4.setText("Alamat");
        jLabel4.setMaximumSize(new java.awt.Dimension(200, 26));
        jLabel4.setMinimumSize(new java.awt.Dimension(200, 26));
        jLabel4.setPreferredSize(new java.awt.Dimension(200, 26));
        company_address.add(jLabel4);

        jSeparator4.setForeground(new java.awt.Color(242, 242, 242));
        jSeparator4.setMaximumSize(new java.awt.Dimension(200, 32767));
        jSeparator4.setMinimumSize(new java.awt.Dimension(200, 10));
        jSeparator4.setPreferredSize(new java.awt.Dimension(100, 10));
        company_address.add(jSeparator4);

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(255, 255, 255));
        jTextField4.setFont(new java.awt.Font("Liberation Sans", 0, 20)); // NOI18N
        jTextField4.setText("Jl. Kemarau panjang No.2");
        jTextField4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextField4.setMaximumSize(new java.awt.Dimension(500, 2147483647));
        jTextField4.setMinimumSize(new java.awt.Dimension(500, 24));
        jTextField4.setPreferredSize(new java.awt.Dimension(300, 24));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        company_address.add(jTextField4);

        setting.add(company_address);

        company_number.setBackground(new java.awt.Color(255, 255, 255));
        company_number.setMaximumSize(new java.awt.Dimension(700, 50));
        company_number.setMinimumSize(new java.awt.Dimension(110, 50));
        company_number.setPreferredSize(new java.awt.Dimension(1182, 50));
        company_number.setLayout(new javax.swing.BoxLayout(company_number, javax.swing.BoxLayout.X_AXIS));

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jLabel6.setText("No. Telp");
        jLabel6.setMaximumSize(new java.awt.Dimension(200, 26));
        jLabel6.setMinimumSize(new java.awt.Dimension(200, 26));
        jLabel6.setPreferredSize(new java.awt.Dimension(200, 26));
        company_number.add(jLabel6);

        jSeparator5.setForeground(new java.awt.Color(242, 242, 242));
        jSeparator5.setMaximumSize(new java.awt.Dimension(200, 32767));
        jSeparator5.setMinimumSize(new java.awt.Dimension(200, 10));
        jSeparator5.setPreferredSize(new java.awt.Dimension(100, 10));
        company_number.add(jSeparator5);

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(255, 255, 255));
        jTextField5.setFont(new java.awt.Font("Liberation Sans", 0, 20)); // NOI18N
        jTextField5.setText("082271449714");
        jTextField5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextField5.setMaximumSize(new java.awt.Dimension(500, 2147483647));
        jTextField5.setMinimumSize(new java.awt.Dimension(500, 24));
        jTextField5.setPreferredSize(new java.awt.Dimension(300, 24));
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        company_number.add(jTextField5);

        setting.add(company_number);

        company_email.setBackground(new java.awt.Color(255, 255, 255));
        company_email.setMaximumSize(new java.awt.Dimension(700, 50));
        company_email.setMinimumSize(new java.awt.Dimension(110, 50));
        company_email.setPreferredSize(new java.awt.Dimension(1182, 50));
        company_email.setLayout(new javax.swing.BoxLayout(company_email, javax.swing.BoxLayout.X_AXIS));

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jLabel8.setText("Email");
        jLabel8.setMaximumSize(new java.awt.Dimension(200, 26));
        jLabel8.setMinimumSize(new java.awt.Dimension(200, 26));
        jLabel8.setPreferredSize(new java.awt.Dimension(200, 26));
        company_email.add(jLabel8);

        jSeparator6.setForeground(new java.awt.Color(242, 242, 242));
        jSeparator6.setMaximumSize(new java.awt.Dimension(200, 32767));
        jSeparator6.setMinimumSize(new java.awt.Dimension(200, 10));
        jSeparator6.setPreferredSize(new java.awt.Dimension(100, 10));
        company_email.add(jSeparator6);

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(255, 255, 255));
        jTextField6.setFont(new java.awt.Font("Liberation Sans", 0, 20)); // NOI18N
        jTextField6.setText("pencariberkah123@gmail.com");
        jTextField6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextField6.setMaximumSize(new java.awt.Dimension(500, 2147483647));
        jTextField6.setMinimumSize(new java.awt.Dimension(500, 24));
        jTextField6.setPreferredSize(new java.awt.Dimension(300, 24));
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        company_email.add(jTextField6);

        setting.add(company_email);

        company_email1.setBackground(new java.awt.Color(255, 255, 255));
        company_email1.setMaximumSize(new java.awt.Dimension(700, 50));
        company_email1.setMinimumSize(new java.awt.Dimension(110, 50));
        company_email1.setPreferredSize(new java.awt.Dimension(1182, 50));
        company_email1.setLayout(new javax.swing.BoxLayout(company_email1, javax.swing.BoxLayout.X_AXIS));

        jLabel10.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jLabel10.setText("Website");
        jLabel10.setMaximumSize(new java.awt.Dimension(200, 26));
        jLabel10.setMinimumSize(new java.awt.Dimension(200, 26));
        jLabel10.setPreferredSize(new java.awt.Dimension(200, 26));
        company_email1.add(jLabel10);

        jSeparator7.setForeground(new java.awt.Color(242, 242, 242));
        jSeparator7.setMaximumSize(new java.awt.Dimension(200, 32767));
        jSeparator7.setMinimumSize(new java.awt.Dimension(200, 10));
        jSeparator7.setPreferredSize(new java.awt.Dimension(100, 10));
        company_email1.add(jSeparator7);

        jTextField7.setEditable(false);
        jTextField7.setBackground(new java.awt.Color(255, 255, 255));
        jTextField7.setFont(new java.awt.Font("Liberation Sans", 0, 20)); // NOI18N
        jTextField7.setText("www.pencariberkah.com");
        jTextField7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextField7.setMaximumSize(new java.awt.Dimension(500, 2147483647));
        jTextField7.setMinimumSize(new java.awt.Dimension(500, 24));
        jTextField7.setPreferredSize(new java.awt.Dimension(300, 24));
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        company_email1.add(jTextField7);

        setting.add(company_email1);

        button_container.setBackground(new java.awt.Color(255, 255, 255));
        button_container.setMaximumSize(new java.awt.Dimension(700, 80));
        button_container.setPreferredSize(new java.awt.Dimension(700, 100));
        button_container.setLayout(new java.awt.BorderLayout());

        jSeparator3.setForeground(new java.awt.Color(242, 242, 242));
        jSeparator3.setMaximumSize(new java.awt.Dimension(32767, 50));
        jSeparator3.setMinimumSize(new java.awt.Dimension(50, 50));
        jSeparator3.setPreferredSize(new java.awt.Dimension(50, 30));
        button_container.add(jSeparator3, java.awt.BorderLayout.PAGE_START);

        btn_logout.setBackground(new java.awt.Color(255, 51, 51));
        btn_logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout.setText("Keluar");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        button_container.add(btn_logout, java.awt.BorderLayout.CENTER);

        setting.add(button_container);

        container_tab.addTab("Setting", setting);

        getContentPane().add(container_tab, "card2");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void jenis_pengiriman_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenis_pengiriman_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jenis_pengiriman_fieldActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.windowManager.showLoginForm();

    }//GEN-LAST:event_btn_logoutActionPerformed

    private void ubah_pengiriman_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubah_pengiriman_buttonActionPerformed
        pengirimanUbah = new PengirimanUbah(this, this.idSelected, this.delivery_table);
        pengirimanUbah.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        pengirimanUbah.setLocationRelativeTo(null);
        pengirimanUbah.setVisible(true);
    }//GEN-LAST:event_ubah_pengiriman_buttonActionPerformed

    private void tambah_pengiriman_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambah_pengiriman_button1ActionPerformed
        insertPersediaanRecord();
        supply_table.setModel(DatabaseConnect.populatePersediaanTable());
        this.setAllTable();
    }//GEN-LAST:event_tambah_pengiriman_button1ActionPerformed

    private void insertPersediaanRecord() {
        // Get input data
        String idBarang = id_barang_field.getText();
        String namaBarang = nama_barang_field.getText();
        String kategori = kategori_field.getText();
        String lokasi = lokasi_field.getText();
        int jumlah = Integer.parseInt(jumlah_field.getText()); // Assuming jumlah is an integer

        // Get the selected date from the JDateChooser
        java.util.Date rawDate = exp_date_field.getDate();

        // Optionally, you can format the date as needed
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String expDate = dateFormat.format(rawDate);

        // Check if any field is empty
        //if (idBarang.isEmpty() || namaBarang.isEmpty() || kategori.isEmpty() || lokasi.isEmpty() || expDate.isEmpty() || jumlah_field.getText().isEmpty()) {
          //  JOptionPane.showMessageDialog(null, "Please fill in all required fields.", "Error", JOptionPane.ERROR_MESSAGE);
            //return;
        //}

        // Send data to query function
        boolean success = DatabaseConnect.insertPersediaanRecord(idBarang, namaBarang, kategori, lokasi, expDate, jumlah);

        // Reset fields if insertion is successful
        if (success) {
            id_barang_field.setText("");
            nama_barang_field.setText("");
            kategori_field.setText("");
            lokasi_field.setText("");
            exp_date_field.setDate(null); // Clear the date chooser
            jumlah_field.setText("");
        }
    }
        
    private void jumlah_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlah_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlah_fieldActionPerformed

    private void ubah_persediaan_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubah_persediaan_buttonActionPerformed
        persediaanUbah = new PersediaanUbah(this, this.idSelected, this.supply_table);
        persediaanUbah.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        persediaanUbah.setLocationRelativeTo(null);
        persediaanUbah.setVisible(true);
    }//GEN-LAST:event_ubah_persediaan_buttonActionPerformed

    private void addnew1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addnew1MouseEntered
    }//GEN-LAST:event_addnew1MouseEntered

    private void cards_contianerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cards_contianerMouseEntered
    }//GEN-LAST:event_cards_contianerMouseEntered

    private void tambah_pengiriman_button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambah_pengiriman_button2ActionPerformed
        insertPermintaanRecord();
        this.updateTableModel();
        this.setAllTable();
    }//GEN-LAST:event_tambah_pengiriman_button2ActionPerformed

    private void jumlah_pesanan_field1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlah_pesanan_field1ActionPerformed
        //
    }//GEN-LAST:event_jumlah_pesanan_field1ActionPerformed

    private void ubah_permintaan_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubah_permintaan_buttonActionPerformed
        permintaanUbah = new PermintaanUbah(this, this.idSelected, this.request_table);
        permintaanUbah.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        permintaanUbah.setLocationRelativeTo(null);
        permintaanUbah.setVisible(true);
    }//GEN-LAST:event_ubah_permintaan_buttonActionPerformed

    public Map<String, String> getDataRowSelected(javax.swing.JTable table, int idSelected){
        // int idSelected = Integer.parseInt(this.idSelected);
        // String requestId = table.getValueAt(idSelected, 1).toString();
        int rowSelected = idSelected;
        int columnCount = table.getColumnCount();
        // String[] valuesRow = new String[columnCount];
        Map<String, String> valuesRow = new HashMap<>();

        for (int i = 0; i < columnCount; i++) {    
            
            String columnName = table.getColumnName(i);
            String columnValue = table.getValueAt(rowSelected, i).toString();
            valuesRow.put(columnName, columnValue);
        }

        return valuesRow;
    }

    private void addnew2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addnew2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_addnew2MouseEntered

    private void status_pemesanan_field1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_status_pemesanan_field1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_status_pemesanan_field1ActionPerformed

    private void tambah_pengiriman_button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambah_pengiriman_button3ActionPerformed
        insertPengirimanRecord();
        delivery_table.setModel(DatabaseConnect.populatePengirimanTable());
        this.setAllTable();
    }//GEN-LAST:event_tambah_pengiriman_button3ActionPerformed

    private void request_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_request_tableMouseClicked
        // TODO add your handling code here:
        // int idx = /
        this.idSelected = this.request_table.getSelectedRow();
        // getDataRowSelected(this.request_table);

    }//GEN-LAST:event_request_tableMouseClicked

    private void supply_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supply_tableMouseClicked
        // TODO add your handling code here:
        this.idSelected = this.supply_table.getSelectedRow();
    }//GEN-LAST:event_supply_tableMouseClicked

    private void delivery_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delivery_tableMouseClicked
        // TODO add your handling code here:
        this.idSelected = this.delivery_table.getSelectedRow();
    }//GEN-LAST:event_delivery_tableMouseClicked

    private void container_tabStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_container_tabStateChanged
        // TODO add your handling code here:
        int selectedTab = this.container_tab.getSelectedIndex();
        if (selectedTab == 0) {
            this.setTableDashboard();
            System.out.println("dashboard updated");
            this.updateDashboardTable();
        }else this.setAllTable();
        fillInputCode();


    }//GEN-LAST:event_container_tabStateChanged
    

    private void fillInputCode(){
        this.kode_pesanan_permintaan.setText(Controller.generateCode("kode_pemesanan", "permintaan", "ORD"));
        this.id_barang_field.setText(Controller.generateCode("id_barang", "persediaan", "BRG"));
        this.kode_pemesanan_field.setText(Controller.generateCode("kode_pemesanan", "pengiriman", "ORD"));
    }

    public void updateTableModel() {
        // Set the table model using the DatabaseConnect.populatePermintaanTable() method
        request_table.setModel(DatabaseConnect.populatePermintaanTable());
        delivery_table.setModel(DatabaseConnect.populatePengirimanTable());
        supply_table.setModel(DatabaseConnect.populatePersediaanTable());
        fillInputCode();
    }
    
    private void insertPermintaanRecord() {
        // Get input data
        String kodePemesanan = kode_pesanan_permintaan.getText();
        String pelanggan = pelanggan_field1.getText();
        String jenisProduk = jenis_produk_field1.getText();
        int jumlahPemesanan = Integer.parseInt(jumlah_pesanan_field1.getText());
        String statusPemesanan = (String) status_pemesanan_field1.getSelectedItem();

        // Get the selected date from the JDateChooser
        java.util.Date rawDate = tanggal_pesanan_field1.getDate();

        //Optionally, you can format the date as needed
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tanggalPemesanan = dateFormat.format(rawDate);


        // Send data to query function
        boolean success = DatabaseConnect.insertPermintaanRecord(kodePemesanan, tanggalPemesanan, jenisProduk, pelanggan, jumlahPemesanan, statusPemesanan);

        // Reset fields if insertion is successful
        if (success) {
            kode_pesanan_permintaan.setText("");
            pelanggan_field1.setText("");
            jenis_produk_field1.setText("");
            jumlah_pesanan_field1.setText("");
            tanggal_pesanan_field1.setDate(null); // Clear the date chooser
        }
    }
    
    private void insertPengirimanRecord() {
        // Get input data
        String kodePemesanan = kode_pemesanan_field.getText();
        String pelanggan = pelanggan_field.getText();
        String jenisProduk = jenis_produk_field.getText();
        String biayaKirim = biaya_pengiriman_field.getText();
        String jasaKirim = (String) jenis_pengiriman_field.getSelectedItem();

        // Get the selected date from the JDateChooser
        java.util.Date rawDate = tanggal_pengiriman_field.getDate();

        //Optionally, you can format the date as needed
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tanggalKirim = dateFormat.format(rawDate);

        // Send data to query function
        boolean success = DatabaseConnect.insertPengirimanRecord(kodePemesanan, pelanggan, jenisProduk, biayaKirim, jasaKirim, tanggalKirim);

        // Reset fields if insertion is successful
        if (success) {
            kode_pemesanan_field.setText("");
            pelanggan_field.setText("");
            jenis_produk_field.setText("");
            biaya_pengiriman_field.setText("");
            tanggal_pengiriman_field.setDate(null); // Clear the date chooser
        }
    }

    private boolean sendToQueryFunction(String kodePemesanan, String pelanggan, String jenisProduk, String biayaKirim, String jasaKirim, String tanggalKirim) {
        // Simulate database insertion
        try {
            // Perform the database insertion logic here
            // For demonstration purposes, we'll print the values instead of actual database operations
            System.out.println("Inserting into database:");
            System.out.println("Kode Pemesanan: " + kodePemesanan);
            System.out.println("Pelanggan: " + pelanggan);
            System.out.println("Jenis Produk: " + jenisProduk);
            System.out.println("Biaya Kirim: " + biayaKirim);
            System.out.println("Jasa Kirim: " + jasaKirim);
            System.out.println("Tanggal Kirim: " + tanggalKirim);

            // Simulate successful insertion
            return true;
        } catch (Exception e) {
            // Log any exceptions that occur during database insertion
            e.printStackTrace();
            return false;
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addnew;
    private javax.swing.JPanel addnew1;
    private javax.swing.JPanel addnew2;
    private javax.swing.JTextField biaya_pengiriman_field;
    private javax.swing.JButton btn_logout;
    private javax.swing.JPanel button_container;
    private javax.swing.JPanel card;
    private javax.swing.JPanel card1;
    private javax.swing.JPanel card2;
    private javax.swing.JPanel cards_contianer;
    private javax.swing.JPanel company_address;
    private javax.swing.JPanel company_data;
    private javax.swing.JPanel company_email;
    private javax.swing.JPanel company_email1;
    private javax.swing.JPanel company_name;
    private javax.swing.JPanel company_number;
    private javax.swing.JTabbedPane container_tab;
    private javax.swing.JPanel dashboard;
    private javax.swing.JTable delivery_table;
    private javax.swing.JLabel delivery_value;
    private com.toedter.calendar.JDateChooser exp_date_field;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JTextField id_barang_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JComboBox<String> jenis_pengiriman_field;
    private javax.swing.JTextField jenis_produk_field;
    private javax.swing.JTextField jenis_produk_field1;
    private javax.swing.JTextField jumlah_field;
    private javax.swing.JTextField jumlah_pesanan_field1;
    private javax.swing.JTextField kategori_field;
    private java.awt.Label kirim1;
    private java.awt.Label kirim10;
    private java.awt.Label kirim11;
    private java.awt.Label kirim12;
    private java.awt.Label kirim14;
    private java.awt.Label kirim15;
    private java.awt.Label kirim16;
    private java.awt.Label kirim17;
    private java.awt.Label kirim18;
    private java.awt.Label kirim19;
    private java.awt.Label kirim2;
    private java.awt.Label kirim3;
    private java.awt.Label kirim4;
    private java.awt.Label kirim5;
    private java.awt.Label kirim6;
    private java.awt.Label kirim7;
    private java.awt.Label kirim8;
    private java.awt.Label kirim9;
    private javax.swing.JTextField kode_pemesanan_field;
    private javax.swing.JTextField kode_pesanan_permintaan;
    private javax.swing.JScrollPane listitem;
    private javax.swing.JScrollPane listitem1;
    private javax.swing.JTextField lokasi_field;
    private javax.swing.JTextField nama_barang_field;
    private javax.swing.JTextField pelanggan_field;
    private javax.swing.JTextField pelanggan_field1;
    private javax.swing.JPanel pengiriman;
    private javax.swing.JTable pengiriman_table_dashboard;
    private javax.swing.JPanel permintaan_container;
    private javax.swing.JPanel permintaan_container1;
    private javax.swing.JPanel permintaan_container2;
    private javax.swing.JTable permintaan_table_dashboard;
    private javax.swing.JTable persediaan_table_dashboard;
    private javax.swing.JLabel product_title;
    private javax.swing.JTable request_table;
    private javax.swing.JLabel request_title;
    private javax.swing.JLabel request_value;
    private javax.swing.JPanel require;
    private javax.swing.JLabel send_title;
    private javax.swing.JPanel setting;
    private javax.swing.JComboBox<String> status_pemesanan_field1;
    private javax.swing.JPanel supply;
    private javax.swing.JTable supply_table;
    private javax.swing.JLabel supply_value;
    private javax.swing.JPanel tables_panel;
    private javax.swing.JButton tambah_pengiriman_button1;
    private javax.swing.JButton tambah_pengiriman_button2;
    private javax.swing.JButton tambah_pengiriman_button3;
    private com.toedter.calendar.JDateChooser tanggal_pengiriman_field;
    private com.toedter.calendar.JDateChooser tanggal_pesanan_field1;
    private java.awt.Label title;
    private java.awt.Label title1;
    private java.awt.Label title2;
    private javax.swing.JPanel title_container;
    private javax.swing.JButton ubah_pengiriman_button;
    private javax.swing.JButton ubah_permintaan_button;
    private javax.swing.JButton ubah_persediaan_button;
    // End of variables declaration//GEN-END:variables
}