/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.kel9.fproject;

/**
 *
 * @author x1nx3r
 */
public class LoginForm extends javax.swing.JFrame {
    private WindowStateManager windowManager; 
    private String username = "";
    private String pword;
    private String uname;
    /**
     * Creates new form LoginForm
     * @param windowManager
     */
    public LoginForm(WindowStateManager windowManager) {
        this.windowManager = windowManager;
        initComponents();               
    }
    private static final String DEFAULT_USERNAME_TEXT = "Username";
    private static final String DEFAULT_PASSWORD_TEXT = "Password";
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        title = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        username_input = new javax.swing.JTextField();
        password_input = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi SCM");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jSeparator1.setMaximumSize(new java.awt.Dimension(32767, 50));
        jPanel1.add(jSeparator1);

        title.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(0, 173, 181));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Aplikasi SCM");
        title.setAlignmentX(0.5F);
        jPanel1.add(title);

        getContentPane().add(jPanel1);

        jSeparator2.setForeground(new java.awt.Color(242, 242, 242));
        jSeparator2.setMaximumSize(new java.awt.Dimension(32767, 50));
        getContentPane().add(jSeparator2);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(500, 400));
        jPanel2.setPreferredSize(new java.awt.Dimension(812, 400));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 30));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator4.setPreferredSize(new java.awt.Dimension(400, 30));
        jPanel2.add(jSeparator4);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 173, 181));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Login Admin");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setPreferredSize(new java.awt.Dimension(400, 26));
        jPanel2.add(jLabel1);

        username_input.setForeground(new java.awt.Color(153, 153, 153));
        username_input.setText(DEFAULT_USERNAME_TEXT);
        username_input.setPreferredSize(new java.awt.Dimension(300, 40));
        username_input.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusUsername(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lostFocusUsername(evt);
            }
        });
        username_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_inputActionPerformed(evt);
            }
        });
        username_input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                typeUsername(evt);
            }
        });
        jPanel2.add(username_input);

        password_input.setForeground(new java.awt.Color(153, 153, 153));
        password_input.setText(DEFAULT_PASSWORD_TEXT);
        password_input.setPreferredSize(new java.awt.Dimension(300, 40));
        password_input.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                password_inputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                password_inputFocusLost(evt);
            }
        });
        password_input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                password_inputKeyTyped(evt);
            }
        });
        jPanel2.add(password_input);

        jButton1.setBackground(new java.awt.Color(0, 173, 181));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Login");
        jButton1.setPreferredSize(new java.awt.Dimension(300, 40));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        getContentPane().add(jPanel2);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void focusPassword(java.awt.event.FocusEvent evt) {
        if (new String(password_input.getPassword()).equals(DEFAULT_PASSWORD_TEXT)) {
            password_input.setText("");
            password_input.setEchoChar('*'); // Mask password
            password_input.setForeground(new java.awt.Color(0, 0, 0));
        }
    }
    
    private void lostFocusPassword(java.awt.event.FocusEvent evt) {
        if (new String(password_input.getPassword()).isEmpty()) {
            password_input.setForeground(new java.awt.Color(153, 153, 153));
            password_input.setText(DEFAULT_PASSWORD_TEXT);
            password_input.setEchoChar((char) 0); // Show text instead of dots
        } else {
            pword = new String(password_input.getPassword());
        }
    }
    
    private void focusUsername(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focusUsername
        // TODO add your handling code here:       
        if (username_input.getText().equals(DEFAULT_USERNAME_TEXT)) {
            username_input.setText("");
            username_input.setForeground(new java.awt.Color(0, 0, 0));
        }               
    }//GEN-LAST:event_focusUsername

    private void lostFocusUsername(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lostFocusUsername
        if (username_input.getText().isEmpty()) {
            username_input.setForeground(new java.awt.Color(153, 153, 153));
            username_input.setText(DEFAULT_USERNAME_TEXT);
        } else {
            username = username_input.getText();
        }
    }//GEN-LAST:event_lostFocusUsername

    private void typeUsername(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_typeUsername
        // TODO add your handling code here:
        uname = this.username_input.getText();
    }//GEN-LAST:event_typeUsername

    private void password_inputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_password_inputKeyTyped
        // TODO add your handling code here:
        char[] passwordChars = password_input.getPassword();
        pword = new String(passwordChars);
    }//GEN-LAST:event_password_inputKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String uname = username_input.getText();
        String pword = new String(password_input.getPassword());

        if (uname.equals(DEFAULT_USERNAME_TEXT)) {
            uname = "";
        }

        if (pword.equals(DEFAULT_PASSWORD_TEXT)) {
            pword = "";
        }

        if (DatabaseConnect.authenticate(uname, pword)) {
            windowManager.showDashboardUI();
        } else {
            System.out.println("USERNAME/PASSWORD SALAH");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void username_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_inputActionPerformed

    private void password_inputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_password_inputFocusGained
        focusPassword(evt);
    }//GEN-LAST:event_password_inputFocusGained

    private void password_inputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_password_inputFocusLost
        lostFocusPassword(evt);
    }//GEN-LAST:event_password_inputFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPasswordField password_input;
    private javax.swing.JLabel title;
    private javax.swing.JTextField username_input;
    // End of variables declaration//GEN-END:variables

    private void print(String username) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
